### ISSUE TITLE
smaller bulb?

### ISSUE THREAD

**Issue by fmarzocca** [jatu-studiobox/node-red-contrib-ui-widget-bulb-basic#1]
Hi, any chance to shrink the bulb smaller than 6x7?

**Comment by jatu-studiobox** [comment]
Thank you for your issue. :) Could you explain more detail about "6x7"?

**Comment by fmarzocca** [comment]
As you can see, the image on left has scrollbar instead of shrinking the bulb

![ce814d89-9c30-46bf-a17a-600490fe7aa9](https://github.com/jatu-studiobox/node-red-contrib-ui-widget-bulb-basic/assets/8530030/041d1bf9-8bb6-416e-ad32-07172abb9c54)

**Comment by jatu-studiobox** [comment]
Thank you very much for your explain. :)

I will check it, and I maybe add more configuration for small size selection.

**Comment by jatu-studiobox** [comment]
Hi, This issue has updated by add small scale bulb. This issue added at version 0.4.0 or latest.

Small scale bulb has display area fixed height at 100px. 

https://github.com/jatu-studiobox/node-red-contrib-ui-widget-bulb-basic/wiki#node-settings

Now this node cannot shrink scale by parent size because css problem. I will try to update for shrinking by parent size again.

Thank you very much :)
